name: generate
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CPPWINRT_VERSION: 2.0.210505.3
jobs:
  generate:
    runs-on: windows-latest
    steps:
      - name: Install wget
        run: choco install wget --no-progress
      - name: Download CppWinRT
        run: wget https://github.com/microsoft/cppwinrt/releases/download/${{ env.CPPWINRT_VERSION }}/Microsoft.Windows.CppWinRT.${{ env.CPPWINRT_VERSION }}.nupkg -O cppwinrt.nupkg
      - name: Setup CppWinRT
        run: Install-Package .\cppwinrt.nupkg
      - name: Generate headers
        run: cppwinrt.exe -in local -verbose
