name: generate
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CPPWINRT_VERSION: 2.0.210505.3
jobs:
  generate:
    runs-on: windows-latest
    steps:
      - run: wget https://github.com/microsoft/cppwinrt/releases/download/2.0.210505.3/Microsoft.Windows.CppWinRT.${{ env.CPPWINRT_VERSION }}.nupkg -O cppwinrt.nupkg
      - name: Setup CppWinRT
        run: Install-Package Microsoft.Windows.CppWinRT cppwinrt.nupkg
      - name: Generate headers
        run: cppwinrt.exe -in local -verbose
