name: generate
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CPPWINRT_VERSION: 2.0.210505.3
jobs:
  generate:
    runs-on: windows-latest
    steps:
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Setup CppWinRT
        run: nuget install Microsoft.Windows.CppWinRT -Version ${{ env.CPPWINRT_VERSION }}
      - name: Generate headers
        run: .\Microsoft.Windows.CppWinRT.${{ env.CPPWINRT_VERSION }}\bin\cppwinrt.exe -in local -verbose
      - name: Test
        shell: bash
        run: ls -laR
